### ISSUE TITLE
Multiple field into one addons

### ISSUE THREAD

**Issue by luxsyp** [OptimalBPM/angular-schema-form-plugins#11]
Hello, 
I'm actually using ASF on a front client app. 
I'm receiving both the Schema and Form from a server, allowing me to make form dynamical.
This is working neatly.
I'm create many addons but I was wondering if there is a way to assign multiple field with one addons. 
for instance 

```
"address": {
    "type": "string",
    "required" : true
  },
  "lon": {
    "type": "number",
    "required": true,
    "readonly": true
  },
  "lat": {
    "type": "number",
    "required": true,
    "readonly": true
  },
```

I would prefer to write one only field for instance:

```
   "address": {
      "type": "googleMapPicker", // <== my addons
      "required" : true
    },
```

Is there any way to access both `lat` and `lon` or the model, and not just $$value$$ within the 

`googleMapPicker` addons ?

**Comment by nicklasb** [comment]
Sorry, I am not sure I understand; Is your question: 
1. Can one add-on access multiple fields in the model, and not only the location where it has been set as the type?  Yes, probably, by accessing the main model, but that doesn't sound nice.
or ...
2. Can one add-on insert any structure in the model at its location? Yes.
 or ..
3. Can another add-on access another add-ons model. Like in 1.

**Comment by luxsypher** [comment]
Yes sorry my question wasn't clear,
The '1' would do what I want. 
I also would be interested by the '3' but I imagine I can make 2 add-ons communicating with events and listener.

**Comment by nicklasb** [comment]
I would put what model fields you want your add-on to use in the
form.field.options. And the find the main model from some parent scope and
add watches or whatever . Don't remember how right now though.
However, traversing like that is sensitive to changes. Perhaps you should
use a central service instead.

**Comment by luxsyp** [comment]
Ok I didn't realize we could simply access the model within the add-on.
It is working like a charm.
